version: "3.7"
services:
  backend:
    build: ./
    ports:
      - "5000:5000"
    depends_on:
    -  db
    command: ["dotnet", "ef", "database update"]

  frontend:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend
    ports:
      - "4000:4000"

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: 'dbSNV'
      MYSQL_ROOT_USER: 'root'
      MYSQL_ROOT_PASSWORD: '123456'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql
volumes:
  my-db: